#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi





# Above is from upstream source ===============================================
# Below is Ray's custom config ================================================

#
# Aliases
#

alias ls=lsd
alias ll='lsd -l'
alias la='lsd -lA'

# lsd https://github.com/lsd-rs/lsd
# -l long format with multiple columns
# -A Show hidden files (entries whose names begin with a dot (‘.’)) except for . and ..
# -h with -l, use unit suffixes: Byte, Kilobyte, Megabyte, etc.
# -G colorized output, same as defining CLICOLOR/COLORTERM in the environment and setting --color=auto

# global
alias -g L="| less"

# all OS
alias c="clear"
alias user="column -ts: /etc/passwd | sort"
alias group="column -ts: /etc/group | sort"

# Python
alias p="python3"
alias p2="python"
alias python="python3"

# Node.js - npm

# export PATH="/opt/homebrew/opt/node@18/bin:$PATH"

# npmlist is nicer than --depth=0
# alias npmls='npm ls --depth=0'
# alias npmlsg='npm ls --depth=0 --location=global'

alias npms='npm start'

alias npmls='npmlist local'
alias npmlsg='npmlist'

alias npml='npm link'
alias npmul='npm unlink'
alias npmulg='npm unlink --location=global'

alias npmo='npm outdated --depth=0'
alias npmog='npm outdated --depth=0 --location=global'

alias npmu='npm update'
alias npmug='npm update --location=global'

alias npmi='npm install'
alias npmig='npm install --location=global'
alias npmis='npm install --save'
alias npmisd='npm install --save-dev'

alias npmui='npm uninstall'
alias npmuig='npm uninstall --location=global'
alias npmuis='npm uninstall --save'
alias npmuisd='npm uninstall --save-dev'

# Node.js - yarn

alias ys='yarn start'
alias yr='yarn run'
alias yi='yarn install'
alias ya='yarn add'
alias yad='yarn add --dev'
alias yx='yarn remove'
alias yls='yarn list --depth=0'
alias yo='yarn outdated'
alias yu='yarn upgrade'

# Node.js - bower
# alias bi='bower install'
# alias bis='bower install --save'
# alias bisd='bower install --save-dev'
# alias bui='bower uninstall'
# alias buis='bower uninstall --save'
# alias buisd='bower uninstall --save-dev'

# Ruby

# Installed via homebrew, not auto added to PATH
export PATH="/opt/homebrew/opt/ruby@3.3/bin:$PATH"

# Other
alias st='subl'
alias hosts='sudo editor /etc/hosts'
alias h='history -10'
alias serve='http-server --address 127.0.0.1 -p 4000 --silent --cors --gzip -c-1' # node
# alias jserve='bundle exec jekyll serve --drafts --full-rebuild'
# alias jserve='bundle exec jekyll serve --drafts'
alias lt='lt --subdomain rayshan --port ' # localtunnel

#
# Directories
# "hash -d" creates named directory shortcuts in zsh, similar to ~ > home directory
# Use in any command, e.g. "cd ~zsh", "ls ~zsh", "vim ~zsh/runcoms/zshrc"
#

# Unix
hash -d git=/home/git/repos
hash -d www=/var/www
hash -d nginx=/etc/nginx
hash -d upstart=/etc/init
hash -d init=/etc/init
hash -d initd=/etc/init.d

hash -d log=/var/log

hash -d zsh=~/.zprezto
hash -d prezto=~/.zprezto

#
# Functions
#

function mkdircd {
  command mkdir $1 && cd $1
}

# npm publish with goodies
# `np` with an optional argument `patch`/`minor`/`major`/`<version>`, defaults to `patch`
# prerequisite: `npm install --location=global trash`
function npmp() {
  trash node_modules &>/dev/null;
  git pull --rebase && \
  npm install && \
  npm test && \
  npm version ${1:-patch} && \
  npm publish && \
  git push --follow-tags
}

#
# Key bindings
# (code could change depending on terminal emulator used)
#

bindkey '^[[1;9C' forward-word			# alt + left
bindkey '^[[1;9D' backward-word			# alt + right

#
# Options
#

# allows # comments inline, useful for cmd history search via "h"
# E.g. ls -l # List files in long format
setopt interactivecomments
